name:                inline-fortran
version:             0.1.0.0
github:              "hasanalrasyid/inline-fortran"
license:             BSD3
author:              "Hasan Al Rasyid"
maintainer:          "hasan@cphys.s.kanazawa-u.ac.jp"
copyright:           "2019 Hasan Al Rasyid"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hasanalrasyid/inline-fortran#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  inline-fortran-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inline-fortran

tests:
  inline-fortran-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inline-fortran
